[project]
name = "self_healing_agent"
version = "0.1.0"
description = "AI agent for self-healing Java Spring Boot apps"
authors = [{ name = "Your Name", email = "you@example.com" }]
dependencies = []
requires-python = ">=3.10"

[tool.adk]
root-agent = "self_healing_agent.main_agent:root_agent"
